-- MySQL Script generated by MySQL Workbench
-- Thu Oct 26 11:52:48 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema geek_project_v2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema geek_project_v2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `geek_project_v2` DEFAULT CHARACTER SET utf8 ;
USE `geek_project_v2` ;

-- -----------------------------------------------------
-- Table `geek_project_v2`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `geek_project_v2`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `last_access` TIMESTAMP NULL,
  `username` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
